-- MySQL Script generated by MySQL Workbench
-- Tue Sep 10 11:14:14 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema alarmSystem
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema alarmSystem
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `alarmSystem` DEFAULT CHARACTER SET utf8 ;
USE `alarmSystem` ;

-- -----------------------------------------------------
-- Table `alarmSystem`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alarmSystem`.`user` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`iduser`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `alarmSystem`.`movementLog`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alarmSystem`.`movementLog` (
  `idmovementLog` INT NOT NULL AUTO_INCREMENT,
  `timestamp` VARCHAR(45) NOT NULL,
  `blob` BLOB NOT NULL,
  PRIMARY KEY (`idmovementLog`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
